package burp.lib.issues

import burp.IHttpRequestResponse
import burp.IHttpService

class PossibleSourceMapIssue(_url: java.net.URL, _httpMessages: Array<IHttpRequestResponse>, _httpService: IHttpService, val extractedComment: String, val sourceMapFileName: String) : BaseIssue(_url, _httpMessages, _httpService) {
    override fun getConfidence() = "Tentative"
    override fun getSeverity() = "Information"

    override fun getIssueName() = "Possible source map"
    override fun getIssueDetail() = "The following source map comment was found: $extractedComment"
    override fun getIssueBackground() = "Source maps are artefacts createed when building web applications that typically include the source code that was used to build the application."

    override fun getRemediationBackground() = "Source maps are typically generated by build tools, such as Webpack."
    override fun getRemediationDetail() = "For production builds, ensure that source maps are not generated by build tooling, or, are not publicly published during application deployment." 
}